# Generated by Django 3.2.5 on 2022-06-03 15:39

import app.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=20)),
                ('profile_img', models.ImageField(default='/images/basic.png', upload_to='images/')),
                ('bg_img', models.ImageField(default='/images/basicbg.png', upload_to='images/')),
                ('bio', models.CharField(default='No Description', max_length=50)),
                ('followers', models.ManyToManyField(blank=True, related_name='_app_profile_followers_+', to='app.Profile')),
                ('following', models.ManyToManyField(blank=True, related_name='_app_profile_following_+', to='app.Profile')),
                ('user', models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date of Post')),
                ('author', models.ForeignKey(default=app.models.Profile, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app.profile')),
                ('likers', models.ManyToManyField(default=models.ForeignKey(default=app.models.Profile, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app.profile'), related_name='likers', to='app.Profile')),
                ('sharers', models.ManyToManyField(default=models.ForeignKey(default=app.models.Profile, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app.profile'), related_name='sharers', to='app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date of Сomment')),
                ('author', models.ForeignKey(default=app.models.Profile, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author1', to='app.profile')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postc', to='app.post')),
            ],
        ),
    ]
